[package]
name = "binaries"
version = "0.1.0"
authors = ["Arbel Israeli <arbel03@gmail.com>"]

[dependencies]
std = { path="std" }

[[bin]]
name = "shell"
path = "shell.rs"

[[bin]]
name = "cat"
path = "cat.rs"